openapi: 3.0.2
info:
  title: FastAPI PresentationsAndAuthor
  version: 0.1.0
paths:
  /presentationsAndAuthor/{title}:
    get:
      summary: Read Presentation
      operationId: read_presentation_presentationsAndAuthor__title__get
      parameters:
        - required: true
          schema:
            title: Title
            type: string
          name: title
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PresentationsAndAuthor'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    PresentationsAndAuthor:
      type: object
      required:        
        - title
        - first_name
        - last_name
        - email  
        - birth_date
        - date
      properties:
        title:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email        
        birth_date:
          type: string
          format: date-time
        date:
          type: string
          format: date
      example:
        title: First Presentation
        first_name: Liam
        last_name: Moore
        email: Liam_Moore4478@iaart.store
        birth_date: '1981-11-27 13:44:56Z'
        date: 23.02.2023 
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
